# Generated by Django 4.2.3 on 2023-07-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='foto',
            field=models.ImageField(null=True, upload_to='mascotas'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='foto',
            field=models.ImageField(null=True, upload_to='propietarios'),
        ),
    ]
